# KallistiOS ##version##
#
# examples/dreamcast/cd/Makefile
# Copyright (C) 2024 Stefanos Kornilios Mitsis Poiitidis
#

all:
	$(KOS_MAKE) -C sound-dma

clean:
	$(KOS_MAKE) -C sound-dma clean

dist:
	$(KOS_MAKE) -C sound-dma dist
